FROM geerlingguy/php-apache:latest

#RUN rm /var/www/html/index.html
COPY . /var/www/html/.

RUN chmod -R 777 /var/www/html/fonts

RUN chmod -R 777 /var/www/html/fullcalendar
RUN chmod -R 777 /var/www/html/fullcalendar/demos
RUN chmod -R 777 /var/www/html/fullcalendar/packages
RUN chmod -R 777 /var/www/html/fullcalendar/vendor

RUN chmod -R 777 /var/www/html/images
RUN chmod -R 777 /var/www/html/images/banner
RUN chmod -R 777 /var/www/html/images/slideshow
RUN chmod -R 777 /var/www/html/images/uploads
RUN chmod -R 777 /var/www/html/images/users


RUN chmod -R 777 /var/www/html/private_files

RUN chmod -R 777 /var/www/html/request
RUN chmod -R 777 /var/www/html/request/passlist

RUN chmod -R 777 /var/www/html/Sound

RUN chmod -R 777 /var/www/html/tinymce

RUN chmod -R 777 /var/www/html/upload

RUN chmod -R 777 /var/www/html/vendor

RUN chmod -R 777 /var/www/html/video

RUN chmod -R 777 /var/www/html/chat

RUN chmod -R 777 /var/www/html/chat/upload

COPY ./ports.conf /etc/apache2/ports.conf
COPY ./apache.conf /etc/apache2/site-enabled/000-default.conf
